# Generated by Django 4.1.3 on 2022-12-11 07:46

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('serial_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=200)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Speaker'), (2, 'CSI')])),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.JSONField(blank=True, default=myapp.models.serial_default, null=True)),
                ('mac_address', models.TextField(blank=True, max_length=10000, null=True)),
                ('mode', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, default='empty', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2022-12-11')),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('activity_count', models.PositiveIntegerField(default=0)),
                ('speaker_count', models.PositiveIntegerField(default=0)),
                ('fall_count', models.PositiveIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
    ]
