# Generated by Django 4.0.6 on 2022-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20, verbose_name='USERID')),
                ('userName', models.CharField(max_length=10, verbose_name='USERNAME')),
            ],
        ),
    ]
