# Generated by Django 4.0.6 on 2022-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_userid_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.CharField(max_length=100),
        ),
    ]
