# Generated by Django 4.0.6 on 2022-08-01 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_users_userid_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userName',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='userId',
        ),
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2022-08-01')),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('activity_count', models.PositiveIntegerField(default=0)),
                ('speaker_count', models.PositiveIntegerField(default=0)),
                ('fall_count', models.PositiveIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
    ]
