# Generated by Django 4.0.6 on 2022-08-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_username_users_user_name_remove_users_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default='2022-08-03'),
        ),
    ]
