# Generated by Django 4.0.6 on 2022-08-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('serial_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=200)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Speaker'), (2, 'CSI')])),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='mac_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='serial_number',
            field=models.JSONField(blank=True, default={'serial_number': 'null', 'type': '1'}, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default='2022-08-08'),
        ),
    ]
