# Generated by Django 4.0.6 on 2022-08-08 02:47

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_raspberrypi_users_mac_address_users_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mac_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='serial_number',
            field=models.JSONField(blank=True, default=myapp.models.serial_default, null=True),
        ),
    ]
