# Generated by Django 4.1.3 on 2022-12-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_users_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mode',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(blank=True, default='empty', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default='2022-12-04'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mac_address',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
