# Generated by Django 4.1.3 on 2022-12-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_users_mode_users_status_alter_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mode',
            field=models.CharField(blank=True, default=False, max_length=255, null=True),
        ),
    ]
