# Generated by Django 4.1.3 on 2022-12-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_users_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mode',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
